FROM archlinux:latest

RUN pacman --noconfirm -Syu

ARG user={{ user }}
ARG repository={{ repository }}

# Create test user
RUN useradd -m ${user} -s /bin/bash \
    && echo "${user}:${user}" | chpasswd \
    && groupadd sudo \
    && gpasswd -a ${user} sudo \
    && echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers
RUN touch /home/${user}/.zshrc \
    && chown -R ${user}:${user} /home/${user}

# Create directory for code
RUN mkdir -p /home/${user}/${repository} \
    && chown -R ${user}:${user} /home/${user}/${repository}
VOLUME ["/home/${user}/${repository}"]

RUN pacman --noconfirm -S ansible sudo

CMD exec /bin/bash -c "trap : TERM INT; sleep infinity & wait"
