#!/usr/bin/env bash

export PYENV_ROOT=${HOME}/.pyenv
export PATH="${PYENV_ROOT}/bin:$PATH"
export PYTHON_VERSION=${PYTHON_VERSION:-2.7.15}

###
# Setup
###
setup() {
    unset -f pyenv
}

###
# Print error into STDERR
###
error() {
    echo "$@" 1>&2
}

###
# Test pyenv is installed on the PATH
###
test_is_installed() {
    echo -n "*** test pyenv binary exists: "
    command -v pyenv > /dev/null || \
        { echo "FAILED"; error "could not find binary on the PATH"; exit 1; }
    echo "OK"
}

###
# Test initializing pyenv
###
test_init() {
    echo -n "*** test pyenv init works: "
    eval "$(pyenv init -)"
    command -v pyenv | grep -q ^pyenv || \
        { echo "FAILED"; error "pyenv function is not defined"; exit 1; }
    echo "OK"
}

###
# Test installing Python
###
test_install_python() {
    echo "*** install Python ${PYTHON_VERSION}..."
    pyenv install ${PYTHON_VERSION} || \
        { error "failed to install Python ${PYTHON_VERSION}"; exit 1; }
}

set -e

setup
test_is_installed
test_init
test_install_python
